### ISSUE TITLE
Latest pydal master breaks dashboard reference fields

### ISSUE THREAD

**Issue by misl6** [web2py/py4web#129]
Latest `pydal` master breaks `py4web` dashboard (reference fields).

This commit reverts a needed change: https://github.com/web2py/pydal/commit/202b55d5e9a4018e23950c60ea56e19324dd8fe0

@mdipierro was just a cleanup or I missed something when I introduced this one?

**Comment by mdipierro** [comment]
I had to remove it because tests were failing. Also it is not necessary, client has that info since client passed that info in the request. Dashboard seems to work for me but I may be wrong. Can this be fixed in the dashboard?

**Comment by mdipierro** [comment]
My bad. I broke this. I fixed it now.

**Comment by misl6** [comment]
Mmm, that's still wrong.
The `field` variable inside that axios callback is the latest iterated `field` inside the loop.
I have a fix for it. Submitting it in ~10 mins.

**Comment by misl6** [comment]
Mmm, that's still wrong.
The `field` variable inside that axios callback is the latest iterated `field` inside the loop.
I have a fix for it. Submitting it in ~10 mins.

**Comment by misl6** [comment]
Did it.
